spring:
  application:
    name: aqua-connect
  datasource:
    url: jdbc:postgresql://localhost:5432/aqua_connect
    username: postgres
    password: Teju@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080

upload:
  dir: uploads